-- MySQL Script generated by MySQL Workbench
-- Mon Oct  5 15:19:17 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ler13c
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ler13c` ;
CREATE SCHEMA IF NOT EXISTS `ler13c` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `ler13c` ;

-- -----------------------------------------------------
-- Table `ler13c`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ler13c`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ler13c`.`customer` (
  `cus_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` INT UNSIGNED ZEROFILL NOT NULL,
  `cus_phone` BIGINT UNSIGNED ZEROFILL NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_balance` DECIMAL(6,2) UNSIGNED NOT NULL,
  `cus_total_sales` DECIMAL(6,2) UNSIGNED NOT NULL,
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ler13c`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ler13c`.`petstore` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ler13c`.`petstore` (
  `pst_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` INT(9) UNSIGNED ZEROFILL NOT NULL,
  `pst_phone` BIGINT UNSIGNED ZEROFILL NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(10,2) UNSIGNED NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ler13c`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ler13c`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ler13c`.`pet` (
  `pet_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT UNSIGNED NOT NULL,
  `cus_id` SMALLINT UNSIGNED NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m','f') NOT NULL,
  `pet_cost` DECIMAL(6,2) UNSIGNED NOT NULL,
  `pet_price` DECIMAL(6,2) UNSIGNED NOT NULL,
  `pet_age` TINYINT UNSIGNED NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y','n') NOT NULL,
  `pet_neuter` ENUM('y','n') NOT NULL,
  `pet_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pet_customer_idx` (`cus_id` ASC),
  INDEX `fk_pet_petstore1_idx` (`pst_id` ASC),
  CONSTRAINT `fk_pet_customer`
    FOREIGN KEY (`cus_id`)
    REFERENCES `ler13c`.`customer` (`cus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_petstore1`
    FOREIGN KEY (`pst_id`)
    REFERENCES `ler13c`.`petstore` (`pst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ler13c`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `ler13c`;
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (NULL, 'Steven', 'Smith', '123 Happy Street', 'Tallahassee', 'FL', 123456789, 1555555555, 'ssmith@gmail.com', 100.00, 25.00, NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (NULL, 'Marsha', 'Johnson', '321 Sad Street', 'Tallahassee', 'FL', 987654321, 1555111111, 'mjohnson@gmail.com', 250.00, 250.00, NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (NULL, 'Leah', 'Allen', '456 Glum Street', 'Miami', 'FL', 098765432, 1555222222, 'lallen@gmail.com', 150.00, 400.00, NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (NULL, 'Linda', 'Roberts', '654 Angry Street', 'Gainesville', 'FL', 234567890, 1555333333, 'lroberts@gmail.com', 300.00, 1500.00, NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (NULL, 'David', 'Doe', '789 Excitement Way', 'Daytona', 'FL', 122333444, 1555444444, 'ddoe@gmail.com', 1000.00, 3000.00, NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (NULL, 'Deb', 'James', '987 Frustration Drive', 'Tallahassee', 'FL', 455566788, 1555777777, 'djames@gmail.com', 500.00, 1000.00, NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (NULL, 'Kara', 'Hunter', '333 Jovial Court', 'Orlando', 'FL', 999000011, 1555665667, 'khunter@gmail.com', 600.00, 2000.00, NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (NULL, 'Breanne', 'Brown', '444 Melancholy Avenue', 'Tampa', 'FL', 122344555, 1555777777, 'bbrown@gmail.com', 400.00, 500.00, NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (NULL, 'Kristi', 'Green', '555 Jolly Way', 'Orlando', 'FL', 677889990, 1555888888, 'kgreen@gmail.com', 200.00, 300.00, NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (NULL, 'Karen', 'White', '777 Lucky Road', 'Tallahassee', 'FL', 123456789, 1555999999, 'kwhite@gmail.com', 300.00, 400.00, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ler13c`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `ler13c`;
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (NULL, 'Fluffy\'s', '1234 Dog Street', 'Tallahassee', 'FL', 123456789, 1555123456, 'fluffys@fluffys.com', 'fluffys.com', 150000.00, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (NULL, 'Petmart', '4321 Cat Street', 'Gainesville', 'FL', 098765432, 1555456789, 'petmart@petmart.com', 'petmart.com', 150000.00, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (NULL, 'Pethaven', '0987 Unicorn Avenue', 'Orlando', 'FL', 234567890, 1555234567, 'pethaven@pethaven.com', 'pethaven.com', 400000.00, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (NULL, 'Petworld', '7890 Pegasus Drive', 'Tampa', 'FL', 987654321, 1555345678, 'petworld@petworld.com', 'petworld.com', 600000.00, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (NULL, 'Pet Place', '5656 Pony Lane', 'Miami', 'FL', 019283746, 1555456789, 'petplace@petplace.com', 'petplace.com', 700000.00, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (NULL, 'Cats n Dogs', '1029 Kitten Way', 'Pensacola', 'FL', 564738291, 1555567890, 'catsndogs@catsndogs.com', 'catsndogs.com', 90000.00, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (NULL, 'Doggy Database', '3847 Kitten Drive', 'Panama City', 'FL', 102938475, 1555098765, 'dd@doggydb.com', 'doggydb.com', 88888.88, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (NULL, 'Kitten Corner', '6565 Kitty Boulevard', 'Daytona', 'FL', 657483920, 1555987654, 'kc@kittencorner.com', 'kittencorner.com', 100000.00, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (NULL, 'Fish Paradise', '4756 Seabreeze Road', 'Tallahassee', 'FL', 123498765, 1555876543, 'fp@fishparadise.com', 'fishparadise.com', 222333.44, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (NULL, 'Whale Emporium', '3829 Mills Avenue', 'Destin', 'FL', 987651234, 1555765432, 'we@whaleemporium.com', 'whaleemporium.com', 8997999.11, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ler13c`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `ler13c`;
INSERT INTO `ler13c`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (NULL, 1, 10, 'hermit crab', 'f', 10.00, 20.00, 1, 'red', '2015-04-25', 'n', 'n', NULL);
INSERT INTO `ler13c`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (NULL, 2, 9, 'fish', 'm', 20.00, 40.00, 1, 'purple', '2015-08-25', 'n', 'n', NULL);
INSERT INTO `ler13c`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (NULL, 3, 8, 'cat', 'f', 100.00, 200.00, 3, 'brown', '2015-06-07', 'y', 'y', NULL);
INSERT INTO `ler13c`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (NULL, 4, 7, 'cat', 'm', 250.00, 500.00, 1, 'white', '2015-07-09', 'y', 'y', NULL);
INSERT INTO `ler13c`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (NULL, 5, 6, 'cat', 'f', 300.00, 600.00, 2, 'black', '2014-12-20', 'y', 'y', NULL);
INSERT INTO `ler13c`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (NULL, 6, 5, 'dog', 'm', 500.00, 1000.00, 4, 'brown', '2014-11-11', 'y', 'y', NULL);
INSERT INTO `ler13c`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (NULL, 7, 4, 'dog', 'f', 1000.00, 2000.00, 3, 'brown', '2015-09-08', 'y', 'y', NULL);
INSERT INTO `ler13c`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (NULL, 8, 3, 'cat', 'm', 500.00, 1000.00, 2, 'golden', '2015-10-05', 'y', 'y', NULL);
INSERT INTO `ler13c`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (NULL, 9, 2, 'fish', 'f', 15.00, 30.00, 1, 'blue', '2015-08-07', 'n', 'n', NULL);
INSERT INTO `ler13c`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (NULL, 10, 1, 'whale', 'm', 5000.00, 9999.99, 50, 'black and white', '2015-09-30', 'y', 'n', NULL);

COMMIT;

